const CLIENT_ID = import.meta.env.VITE_SPOTIFY_CLIENT_ID
const REDIRECT_URI = 'http://127.0.0.1:5173/callback'

function generateRandomString(length) {
  const possible =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'

  const values = crypto.getRandomValues(new Uint8Array(length))

  return values.reduce(
    (acc, x) => acc + possible[x % possible.length],
    ''
  )
}

async function sha256(plain) {
  const encoder = new TextEncoder()
  const data = encoder.encode(plain)

  return window.crypto.subtle.digest('SHA-256', data)
}

function base64encode(input) {
  return btoa(String.fromCharCode(...new Uint8Array(input)))
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
}

export async function loginWithSpotify() {

  // Random secret generated by OUR browser
  const codeVerifier = generateRandomString(64)

  // Hash of that secret
  const hashed = await sha256(codeVerifier)
  const codeChallenge = base64encode(hashed)

  // We need the original secret later
  localStorage.setItem('code_verifier', codeVerifier)

  const params = new URLSearchParams({
    client_id: CLIENT_ID,
    response_type: 'code',
    redirect_uri: REDIRECT_URI,

    scope: 'user-top-read user-read-recently-played',

    code_challenge_method: 'S256',
    code_challenge: codeChallenge,
  })

  window.location.href =
    `https://accounts.spotify.com/authorize?${params.toString()}`
}


export async function getAccessToken(code) {
  const codeVerifier = localStorage.getItem('code_verifier')

  const params = new URLSearchParams({
    client_id: CLIENT_ID,
    grant_type: 'authorization_code',
    code: code,
    redirect_uri: REDIRECT_URI,
    code_verifier: codeVerifier,
  })

  const response = await fetch(
    'https://accounts.spotify.com/api/token',
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: params,
    }
  )

  const data = await response.json()

  localStorage.setItem('access_token', data.access_token)

  return data.access_token
}

export async function getTopArtists(accessToken) {
  const response = await fetch(
    'https://api.spotify.com/v1/me/top/artists?limit=10&time_range=short_term',
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  )

  if (!response.ok) {
    throw new Error('Failed to fetch top artists')
  }

  return response.json()
}

export async function getPlaylistTracks(accessToken, playlistId) {
  let url =
    `https://api.spotify.com/v1/playlists/${playlistId}/items?limit=50`

  const allItems = []

  while (url) {
    const response = await fetch(url, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    })

    if (!response.ok) {
      throw new Error(
        `Failed to fetch playlist: ${response.status}`
      )
    }

    const data = await response.json()

    allItems.push(...data.items)

    url = data.next
  }

  return {
    items: allItems
  }
}